# dockers/xdev/Dockerfile

FROM rubicks/dev
MAINTAINER rubicks

RUN sudo apt-get -y update       && \
    sudo apt-get -y dist-upgrade && \
    sudo apt-get -y install         \
         libX11-dev                 \
         libfltk1.3-dev             \
         libfontconfig1-dev         \
         libglu1-mesa-dev           \
         libice-dev                 \
         libjpeg-dev                \
         libpng-dev                 \
         libx11-dev                 \
         libxcursor-dev             \
         libxext-dev                \
         libxft-dev                 \
         libxi-dev                  \
         libxinerama-dev            \
         libxrender-dev             \
         libz-dev                   \
         mesa-common-dev

CMD /bin/bash
